<a href="https://colab.research.google.com/github/Satyajit99p/Intro-DL-CNN/blob/master/CNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import keras

In [2]:
from keras.datasets import mnist

In [3]:
from keras.utils import to_categorical
(train_images,train_labels),(test_images,test_labels)=mnist.load_data()

11493376/11490434 [==============================] - 0s 0us/step


In [67]:
train_images.shape

(60000, 28, 28, 1)

In [68]:
train_images[5].shape

(28, 28, 1)

In [69]:
train_images[0]

array([[[0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00]],

       [[0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0

In [70]:
train_labels[0]

5

In [71]:
train_images=train_images.reshape(60000,28,28,1)

In [72]:
train_images.shape

(60000, 28, 28, 1)

In [73]:
train_images[0]

array([[[0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00]],

       [[0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0

In [74]:
train_images=train_images.astype('float32')/255
test_images=test_images.reshape((10000,28,28,1))
test_images=test_images.astype('float32')/255

In [75]:
train_images[0]

array([[[0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00]],

       [[0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0.00000000e+00],
        [0

In [76]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [81]:
train_labels=to_categorical(train_labels)
test_labels=to_categorical(test_labels)

In [82]:
from keras import models
from keras import layers

model=models.Sequential()
model.add(layers.Conv2D(32, (3, 3),activation='relu', input_shape=(28, 28, 1)))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(16, (5, 5),activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))

In [83]:
model.summary()

Model: "sequential_8"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_14 (Conv2D)           (None, 26, 26, 32)        320       
_________________________________________________________________
max_pooling2d_14 (MaxPooling (None, 13, 13, 32)        0         
_________________________________________________________________
conv2d_15 (Conv2D)           (None, 9, 9, 16)          12816     
_________________________________________________________________
max_pooling2d_15 (MaxPooling (None, 4, 4, 16)          0         
Total params: 13,136
Trainable params: 13,136
Non-trainable params: 0
_________________________________________________________________


In [84]:
model.add(layers.Flatten())

model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(10, activation='softmax'))

In [85]:
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])
model.fit(train_images, train_labels, epochs=50, batch_size=64)

Epoch 1/50
938/938 [==============================] - 46s 49ms/step - loss: 2.3016 - accuracy: 0.1121
Epoch 2/50
938/938 [==============================] - 46s 49ms/step - loss: 2.3013 - accuracy: 0.1124
Epoch 3/50
938/938 [==============================] - 51s 54ms/step - loss: 2.3013 - accuracy: 0.1124
Epoch 4/50
938/938 [==============================] - 46s 49ms/step - loss: 2.3014 - accuracy: 0.1124
Epoch 5/50
938/938 [==============================] - 46s 49ms/step - loss: 2.3013 - accuracy: 0.1124
Epoch 6/50
938/938 [==============================] - 46s 49ms/step - loss: 2.3013 - accuracy: 0.1124
Epoch 7/50
938/938 [==============================] - 46s 49ms/step - loss: 2.3013 - accuracy: 0.1124
Epoch 8/50
938/938 [==============================] - 45s 48ms/step - loss: 2.3013 - accuracy: 0.1124
Epoch 9/50
938/938 [==============================] - 46s 49ms/step - loss: 2.3013 - accuracy: 0.1124
Epoch 10/50
938/938 [==============================] - 46s 49ms/step - loss: 2.301

In [86]:
test_loss,test_acc=model.evaluate(test_images,test_labels)

313/313 [==============================] - 3s 9ms/step - loss: 2.3010 - accuracy: 0.1135


In [87]:
test_images[0].shape

(28, 28, 1)

In [88]:
test_acc

0.11349999904632568

In [90]:
test_loss

2.3009958267211914

In [91]:
test_data=train_images[10].reshape(1,28,28,1)

In [92]:
model.predict_classes(test_data)

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).


array([1])

In [105]:
train_labels[10]

array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [106]:
train_labels[10].argmax()

3

In [120]:
test_data=test_images

In [121]:
test_data.shape

(10000, 28, 28, 1)

In [122]:
pred=model.predict_classes(test_data)

In [123]:
pred

array([1, 1, 1, ..., 1, 1, 1])

In [124]:
from sklearn import metrics
matrix=metrics.confusion_matrix(test_labels.argmax(axis=1),pred)

In [ ]:
matrix